### ISSUE TITLE
Do we need four different packages?

### ISSUE THREAD

**Issue by erikng** [macadmins/python#8]
We currently have four. Do we need them? Maybe 2? Maybe 1?

**Comment by bp88** [comment]
There are 4 packages that can be generated: No Customization > Minimal > Recommended > Opinionated. Each is respectively a subset of the next. To err on the sake of simplicity, would it make more sense to get it down to two flavors? Minimal and Opinionated. Here’s my rationale
Minimal should be self-explanatory. It covers what the original intent of the Relocatable Python covers.

If someone wants plain Python for managing their Macs, they can very well just rely on the Xcode Command Line Tools which automatically install Python 3. Seems like a much simpler path of least resistance there.

The difference between Recommended and Opinionated is 10 additional modules:
- arrow
- atomicwrites
- boto
- funcsigs
- pytest
- pytest-docker
- python-dotenv
- rsa
- slacker
- Sphinx

Since Recommended is just a subset of Opinionated in this case, wouldn’t it be simpler to just make Opinionated the actual “recommended” download. What would be the concern in including the extra modules that are not needed?

**Comment by natewalck** [comment]
I think only `Recommended` should be provided as the reference managed python implementation. If anything is needed outside of that, a virtual environment can be used(or a pex or a pyinstaller bundle).

There are a lot of solutions for using stuff that isn't included by default.

Also, it should be clear that installing stuff directly to this python is a bad idea and why that is so.

**Comment by erikng** [comment]
FWIW those 10 modules double the size of the framework file.

I would lean on recommended as well, mainly from my discoveries in building this.

Thanks,
Erik Gomez
________________________________

**Comment by erikng** [comment]
The build process will only be building the `Recommended` workflow moving forward. People who need the other options can build it themselves as they will likely have complex requirements and the skillsets to maintain those requirements.
